### ISSUE TITLE
网关模式问题

### ISSUE THREAD

**Issue by m2acgi** [gfreezy/seeker#104]
请问网关模式就是透明代理网关吗？支持透明代理 tcp, udp, icmp 协议吗？网关模式还需要写 iptables 规则吗？

**Comment by gfreezy** [comment]
只支持 tcp、udp，不需要写 iptables 了，程序会自己设置路由表

**Comment by m2acgi** [comment]
@ficapy 谢谢，请问哪里有网站模式的相关文档？

**Comment by gfreezy** [comment]
https://github.com/gfreezy/seeker#%E4%BB%A3%E7%90%86%E5%B1%80%E5%9F%9F%E7%BD%91%E5%86%85%E5%85%B6%E4%BB%96%E6%9C%BA%E5%99%A8

**Comment by m2acgi** [comment]
我看说明，网关模式是不支持客户端使用 IP 访问吗？例如局域网的一台 PC 将它的网关配置为 seeker 的 IP，然后这台 PC 上的某个软件需要通过 IP 访问互联网上的某个服务，这个是不支持的吗？

**Comment by gfreezy** [comment]
```
sudo route -n add -net 8.8.8.8 utun4
```

应该手动把 IP 加到路由表就可以了，试一下

**Comment by m2acgi** [comment]
是在 seeker 所在的主机上加吗？

**Comment by gfreezy** [comment]
对
