### ISSUE TITLE
Ping shadowsocks server name?

### ISSUE THREAD

**Issue by fbion** [gfreezy/seeker#110]
配置文件里面只有两个server
servers:
  - name: socks5 proxy server
    addr: 127.0.0.1:7890
    protocol: Socks5  # Https or Http or Socks5 or Shadowsocks

  - name: socks5 proxy server
    addr: 127.0.0.1:7890
    protocol: Socks5  # Https or Http or Socks5 or Shadowsocks

日志里面为什么会显示
INFO seeker::server_chooser: Ping shadowsocks server name="socks5 proxy server" server=127.0.0.1:7890 latency=1010

**Comment by gfreezy** [comment]
默认会自动从多个 server 里面选择速度较快的那个。这里的 ping 含义是 HTTP GET 以下 4 个网址总耗时。

```
google.com:80
twitter.com:80
github.com:80
youtube.com:80
```
