### ISSUE TITLE
ip 限制问题

### ISSUE THREAD

**Issue by johnnyhansen-away** [gfreezy/seeker#131]
你好, 我想问一下seeker为什么不支持ip的转发, 如果我想将指定ip的数据也加入到代理范围内, 请问我应该怎么做

**Comment by gfreezy** [comment]
应该是已经支持了的

`
  - 'IP-CIDR,19.23.212.0/16,PROXY'
  - 'IP-CIDR,19.23.21.0/16,PROBE'
  `

**Comment by johnnyhansen-away** [comment]
手动点赞
