### ISSUE TITLE
全局代理

### ISSUE THREAD

**Issue by johnnyhansen-away** [gfreezy/seeker#132]
你好, 请问咱们的程序能做到在mac上的全局代理么, 所有软件在请求配置好的域名或者ip时都能够通过咱们的程序进行代理, 包括在对目标机器的ping 操作, 支持自定义代理协议么, 谢谢

**Comment by johnnyhansen-away** [comment]
还有支持https么

**Comment by gfreezy** [comment]
目前只支持 shadowsocks 、socks 5、http 代理服务器。
所有 app 都可以代理。具体使用可以参考 readme 或者可以看下 https://github.com/gfreezy/seeker/blob/master/sample_config.yml

**Comment by johnnyhansen-away** [comment]
> 目前只支持 shadowsocks 、socks 5、http 代理服务器。 所有 app 都可以代理。具体使用可以参考 readme 或者可以看下 https://github.com/gfreezy/seeker/blob/master/sample_config.yml

你好, 对于https的代理咱们有计划支持么, 还有ping操作

**Comment by gfreezy** [comment]
目前是支持https代理的。ping需要server端支持，http、https、shadowsocks 标准 server 都不支持 ping。
