### ISSUE TITLE
mac 编译报错

### ISSUE THREAD

**Issue by johnnyhansen-away** [gfreezy/seeker#133]
编译时报错:
a@hansen seeker % sudo cargo build --release
error[E0658]: deriving `Default` on enums is experimental
  --> config/src/rule.rs:17:68
   |
17 | #[derive(Eq, PartialEq, Copy, Clone, Debug, Hash, PartialOrd, Ord, Default)]
   |                                                                    ^^^^^^^
   |
   = note: see issue #86985 <https://github.com/rust-lang/rust/issues/86985> for more information
   = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.
error: could not compile `config` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
a@hansen seeker % rustc --explain E0658
===================================================
a@hansen seeker % cargo version             
cargo 1.60.0 (d1fd9fe2c 2022-03-01)

**Comment by gfreezy** [comment]
rust 版本太低了。更新到最新的 stable 版本
