### ISSUE TITLE
使用IP代理不生效

### ISSUE THREAD

**Issue by lflish** [gfreezy/seeker#155]
我的域名是 test.vpn.com 对应的IP地址是 192.168.1.2,按如下配置
 ```yaml
rules:
   - 'DOMAIN,test.vpn.com,PROXY'
   - 'IP-CIDR,192.168.1.2/32,PROXY'
```
curl http://test.vpn.com 会走代理，正常返回数据
curl http://192.168.1.2 返回报错

使用的是socks5代理，在socks5服务器没有抓到socks5的流量的，通过域名访问可以抓到
看了下路由表，是有这条路由的，我系统是manjaro

**Comment by gfreezy** [comment]
完整配置文件是什么

**Comment by lflish** [comment]
verbose: false
dns_start_ip: 11.0.0.10
dns_servers:  # dns 服务器列表，如果不设置，会自动从系统获取。最好指定，否则 Wi-Fi 切换时可能会出现问题。
  - 192.168.20.170:53
dns_timeout: 1s
# redir 模式使用 iptable 的 redirect 功能： iptables -t nat -A PREROUTING -d 11.0.0.0/16 -p tcp -j REDIRECT --to-ports 1300
# redir 模式下只支持 tcp 流量。默认使用 tun 模式。特殊设备不支持 tun 的情况，可以使用 redir 模式。
redir_mode: false
tun_bypass_direct: false  # 直连的域名直接返回真实IP，不走tun 
tun_name: utun0
tun_ip: 11.0.0.1
tun_cidr: 11.0.0.0/16
dns_listen: 0.0.0.0:53
gateway_mode: true
probe_timeout: 200ms
ping_timeout: 2s
connect_timeout: 2s
read_timeout: 300s
write_timeout: 300s
max_connect_errors: 2
geo_ip: path/to/geoip.mmdb # geoip 数据库路径，如果使用相对路径，相对于可执行文件的路径。默认会搜索可执行文件同级目录下的 geoip.mmdb 文件
ping_urls:
  - host: www.facebook.com
    port: 80
    path: /
  - host: www.youtube.com
    port: 80
    path: /
  - host: twitter.com
    port: 80
    path: /

#remote_config_urls:  # ss 订阅地址，启动时自动拉群配置，并将配置的服务器地址自动加入服务器列表
  #- https://addr-to-ss-subscribe-url.com

servers:
- name: socks5 proxy server
  addr: 192.168.20.170:18080
  protocol: Socks5  # Https or Http or Socks5 or Shadowsocks

rules:
  - 'DOMAIN,test.vpn.com,PROXY'
  - 'IP-CIDR,192.168.1.2/32,PROXY'
