### ISSUE TITLE
thread 'main' panicked at 'internal error: entered unreachable code', config/src/rule.rs:141:18

### ISSUE THREAD

**Issue by panw3i** [gfreezy/seeker#156]
thread 'main' panicked at 'internal error: entered unreachable code', config/src/rule.rs:141:18
stack backtrace:
   0:        0x104cd3890 - __mh_execute_header
   1:        0x104a8f91c - __mh_execute_header
   2:        0x104cb656c - __mh_execute_header
   3:        0x104cd36ac - __mh_execute_header
   4:        0x104cbeb14 - __mh_execute_header
   5:        0x104cbe7fc - __mh_execute_header
   6:        0x104cbf1a8 - __mh_execute_header
   7:        0x104cd4198 - __mh_execute_header
   8:        0x104cd39c0 - __mh_execute_header
   9:        0x104cbee1c - __mh_execute_header
  10:        0x104fd0c30 - __mh_execute_header
  11:        0x104fd0ca0 - __mh_execute_header
  12:        0x104a7cb0c - __mh_execute_header
  13:        0x104a7d04c - __mh_execute_header
  14:        0x104a69950 - __mh_execute_header
  15:        0x104a5d5d4 - __mh_execute_header
  16:        0x104a6d00c - __mh_execute_header
  17:        0x104a7f05c - __mh_execute_header
  18:        0x104c7d18c - __mh_execute_header
  19:        0x104c19b4c - __mh_execute_header
  20:        0x104c1f62c - __mh_execute_header
  21:        0x104cbca60 - __mh_execute_header
  22:        0x104c97138 - __mh_execute_header

**Comment by gfreezy** [comment]
action 只支持 PROBE PROXY DIRECT REJECT 四种，应该是手误打了其他的东西
