### ISSUE TITLE
如何指定让特定域名的DNS查询走代理？

### ISSUE THREAD

**Issue by yaosunwen** [gfreezy/seeker#181]
从家里通过SSH连接公司网络，开动态socks代理，但公司内部域名无法解析，不知道怎么配置可以让这部分域名走socks代理？

**Comment by gfreezy** [comment]
# 修改 DNS

```
dns_servers:
  - 223.5.5.5:53
  - 114.114.114.114:53
  - tcp://114.114.114.114:53
```
删掉 dns_servers 的配置，配置文件不指定 DNS 的情况，应该会用默认 DNS。或者把内部 DNS 加到第一位。默认 DNS 应该就可以解析内部域名。

# 如果不行，再做下面的步骤
tun_bypass_direct 设置为 true，然后在规则里面把内部域名设置为 DIRECT。这种情况下内部域名会直接返回真实 IP。

```
tun_bypass_direct: true  # 直连的域名直接返回真实IP，不走tun
```

```
  - 'DOMAIN-KEYWORD,域名,DIRECT'
```

**Comment by yaosunwen** [comment]
试了一下好像不行，可能我之前没有描述清楚，我的场景是这样的：
家里和公司都是私有网络地址，家里是192.168.x.x，公司是10.x.x.x，比如家里的机器ip是192.168.0.1，公司的机器ip是10.0.0.1，公司在10.0.0.53设有一个DNS服务器，通过跳板机建立了192.168.0.1到10.0.0.1之间的ssh连接，并且在192.168.0.1:1080端口开启了socks代理协议，因此我通过设置浏览器的socks协议代理是可以从192.168.0.1访问公司的内部网站的，但是我想从192.168.0.1用透明代理方式访问10.x.x.x的所有内部网站，其他公开网站，比如baidu.com，走直连。

**Comment by gfreezy** [comment]
1. ssh 连接需要继续保留
2. 浏览器继续使用 socks 代理，规则修改为公司内网域名都走代理，其他域名直连
3. seeker 正常开启，把跳板机域名设置成 DIRECT，如果跳板机是 IP，不需要特殊配置。

这样就可以实现浏览器内公司域名可以访问，其他走 seeker。但是浏览器以外无法访问公司网络。

**Comment by yaosunwen** [comment]
感谢回复，目前也是这么做的，只是用其他软件要连接公司内部时没那么方便，但基本够用。

**Comment by gfreezy** [comment]
https://github.com/gfreezy/seeker/pull/182 

这个 PR 增加了 proxy group 的支持。

现在可以在 seeker 里面创建 2 个 proxy group：

1. internal-group  用来访问公司内网，proxy server 设置为 ssh 打洞的 socks 代理
2. other-group 另外一个 proxy group 用来日常访问

然后在规则里面，将公司内网域名都设置成

`PROXY(internal-group)`

默认设置成

`PROBE(other-group)`
