### ISSUE TITLE
在mac os上tun接口支持ip访问

### ISSUE THREAD

**Issue by fbion** [gfreezy/seeker#51]
seeker.conf :
pass out log on en0 route-to utun4 inet proto { tcp } to any port {80,443}

期待支持socks5 udp... for chrome youtube quic
#pass out log on en0 route-to utun4 inet proto { udp } to any port {80,443, 123}

是否支持ipv6?
#pass out log on en0 route-to utun4 inet6 proto { tcp } to any port {80,443}

pfctl -e -f seeker.conf

**Comment by fbion** [comment]
上面的规则会route to所有80 443 123 tcp udp流量去utun4
包括PROBE直连，这样会形成回环
解决办法是
为PROBE直连 增加一个代理出口
可以架设在其它设备上
PROBE直连 -> 192.168.1.2:1080
比如这样

**Comment by gfreezy** [comment]
一般来说网络访问都会先走 DNS， seeker 目前不支持捕获直接 IP 的访问。

我们你配置里面是 80 443 端口，什么场景下 80 443 端口直接使用 IP 而不是域名

**Comment by fbion** [comment]
> 一般来说网络访问都会先走 DNS， seeker 目前不支持捕获直接 IP 的访问。
> 
> 我们你配置里面是 80 443 端口，什么场景下 80 443 端口直接使用 IP 而不是域名

telegram

**Comment by gfreezy** [comment]
增加了 socks5 代理支持 #52

**Comment by gfreezy** [comment]
## 指定 IP 或某网段走代理
修改路由表，将希望走代理的 IP 或者网段路由到虚拟网卡。如果使用了本机 socks5 代理，则必须确保 socks5 不会直连加入路由表的网段，否则会死循环。

比如我希望 `8.8.8.8` 这个 IP 所有流量都走代理，且使用本地 clashx 创建的 socks5 代理：

1. 将 `8.8.8.8` 路由到 utun4

    ```shell script
    sudo route -n add -net 8.8.8.8 utun4
    ```

2. 修改 clashx 的规则，增加下面一条

    ```
   - 'IP-CIDR,8.8.8.8/32,DIRECT'
   ```
