### ISSUE TITLE
socks5优先问题

### ISSUE THREAD

**Issue by fbion** [gfreezy/seeker#53]
sample_config.yml
只修改了
socks5_server:
  addr: domain-or-ip-to-socks5-server:port
  addr: 127.0.0.1:1080

sudo ./seeker-osx -c sample_config.yml 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("missing field `shadowsocks_servers`", Some(Pos { marker: Marker { index: 12, line: 1, col: 12 }, path: "." }))', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

然后修改
shadowsocks_configs
shadowsocks_servers

sudo ./seeker-osx -c sample_config.yml 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("invalid value: domain-or-ip-to-ss-server:port, ip:port or domain:port", Some(Pos { marker: Marker { index: 398, line: 21, col: 8 }, path: "shadowsocks_servers[0]" }))', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

这个优先判断有问题

**Comment by gfreezy** [comment]
贴一下完整的配置文件
