### ISSUE TITLE
darwin上的sysconfig问题

### ISSUE THREAD

**Issue by raintean** [gfreezy/seeker#63]
darwin上直接指定的wifi网卡, 不适用其他连接方式, 可以先获取主网卡, 再修改dns, 另外程序退出恢复dns, 如果使用信号监听, 在注销的时候可能会监听不到, 导致dns不恢复, 我以前碰到过这样的问题, 提个醒...

**Comment by gfreezy** [comment]
自动获取主网卡再修改DNS

https://github.com/gfreezy/seeker/pull/66

**Comment by LuoZijun** [comment]
采用 daemon 程序的方式？

`seeker` 运行的时候使用 `std::process::Command` 调用 seeker 自己，加上 `--daemon` 参数运行。

这样程序不管什么情况被退出，上层的 `seeker` 总可以知道。

```
seeker
    seeker --daemon
```

**Comment by raintean** [comment]
> 采用 daemon 程序的方式？
> 
> `seeker` 运行的时候使用 `std::process::Command` 调用 seeker 自己，加上 `--daemon` 参数运行。
> 
> 这样程序不管什么情况被退出，上层的 `seeker` 总可以知道。
> 
> ```
> seeker
>     seeker --daemon
> ```

注销或者关机的情况下, 来不及的.

**Comment by LuoZijun** [comment]
@raintean 你说的注销接收不到，可有可以复现的案例？以及附上相应的平台信息。

**Comment by gfreezy** [comment]
> 采用 daemon 程序的方式？
> 
> `seeker` 运行的时候使用 `std::process::Command` 调用 seeker 自己，加上 `--daemon` 参数运行。
> 
> 这样程序不管什么情况被退出，上层的 `seeker` 总可以知道。
> 
> ```
> seeker
>     seeker --daemon
> ```

daemon 运行是什么意思，fork 以后父进程退出，让 pid 0 接管进程？但是命令行归根到底应该都是走的 signal ，如果 daemon 可以收到 signal，直接启动应该也可以收到 signal 的？

**Comment by LuoZijun** [comment]
@gfreezy 程序调用程序自己，在调用自己时，会传递一个参数，避免无限调用。
然后父进程 等待子进程结束。如果子进程被意外终止，如 panic 什么的，并且信号也没有收到。那么在父进程也许还可以做一些措施挽救？

当然，@raintean 能把那个事情说得更清楚一些就更好咯。比如什么平台之类的。
